# Generated by Django 3.2.5 on 2022-08-08 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_body_image',
            field=models.FileField(blank=True, help_text='Only PNG, JPG, JPEG format supported', null=True, upload_to='aboutimage', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='About section body image'),
        ),
        migrations.AlterField(
            model_name='general',
            name='hero_image_field',
            field=models.FileField(blank=True, help_text='Only PNG, JPG, JPEG format supported', null=True, upload_to='homepageimage', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Home Background hero image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, help_text='Only PNG, JPG, JPEG format supported', null=True, upload_to='project_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='references',
            name='person_image',
            field=models.FileField(blank=True, help_text='Only PNG, JPG, JPEG format supported', null=True, upload_to='ref_person_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Reference Person Image'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, help_text='Only PDF format supported', null=True, upload_to='resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF'])], verbose_name='Upload Resume/ CV'),
        ),
    ]
