# Generated by Django 3.2.5 on 2021-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('Detail', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='ctime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
