# Generated by Django 3.2.5 on 2022-07-20 05:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=300, verbose_name='Main Title')),
                ('advertise_title', models.CharField(max_length=300, verbose_name='Advertisement Title')),
                ('terms', tinymce.models.HTMLField(verbose_name='Enter terms and conditions')),
                ('hero_image_field', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='Homepage_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Home Background hero image')),
                ('policy', tinymce.models.HTMLField(verbose_name='Enter policy')),
                ('home_video_link', models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=250, verbose_name='Enter youtube link for home video')),
                ('phone', models.CharField(max_length=20, verbose_name='Company official Mobile/ Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Company official email')),
                ('address', models.CharField(max_length=300, verbose_name='Full Address ')),
                ('facebook_link', models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Facebook Link ')),
                ('whatsapp_link', models.CharField(max_length=300, verbose_name='Whatsapp Link/Mobile number')),
                ('instagram_link', models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Instagram Link')),
                ('linkedin_link', models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Linkedin Link')),
                ('youtube_link', models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Youtube Link')),
                ('mode', models.CharField(choices=[('1', 'production'), ('2', 'development')], max_length=100, verbose_name='Select Mode')),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('last_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_about', models.TextField(help_text='Not more than 300 character', max_length=300, verbose_name='Site Short About')),
                ('happy_clients', models.IntegerField(blank=True, null=True, verbose_name='Enter Happy clients Count')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Enter the company work of experiences')),
                ('about_body_image', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='About_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='About section body image')),
                ('long_about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Site Long About')),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('last_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
