# Generated by Django 3.2.5 on 2022-07-20 07:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_about_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=300, verbose_name='Enter Institute Name')),
                ('degree_full', models.CharField(max_length=300, verbose_name='Enter Your Degree')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Join Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('summery', tinymce.models.HTMLField(verbose_name='Share Education Summery')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=300, verbose_name='Reference Person Name')),
                ('person_designation', models.CharField(max_length=300, verbose_name='Person Designation')),
                ('person_image', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='ref_person_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Reference Person Image')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company or Organization Name')),
                ('person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Reference Person's Email")),
                ('person_phone', models.CharField(blank=True, max_length=300, null=True, verbose_name="Reference Person's Phone/Mobile Number")),
                ('quotes', tinymce.models.HTMLField(blank=True, null=True, verbose_name="Reference Person's testimonials")),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_category_name', models.CharField(help_text='ex. Framework, Database, etc..', max_length=300, verbose_name='Enter Skills Category')),
                ('title', models.CharField(max_length=300, verbose_name='Skills Title')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('Advance', 'Advance'), ('Expert', 'Expert')], max_length=100, verbose_name='Skills Level')),
                ('level_value', models.IntegerField(verbose_name='Skills Level Value')),
                ('bootstrap_bg', models.CharField(choices=[('bg-primary', 'bg-primary'), ('bg-secondary', 'bg-secondary'), ('bg-success', 'bg-success'), ('bg-danger', 'bg-danger'), ('bg-warning', 'bg-warning'), ('bg-info', 'bg-info'), ('bg-light', 'bg-light'), ('bg-dark', 'bg-dark'), ('bg-white', 'bg-white')], max_length=100, verbose_name='Select Background Color')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=300, verbose_name='Enter Designation/Position')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company or Organization Name')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Join Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('responsibilities', tinymce.models.HTMLField(verbose_name='Company/Organization Responsibilities')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_clients',
        ),
        migrations.RemoveField(
            model_name='general',
            name='home_video_link',
        ),
        migrations.RemoveField(
            model_name='general',
            name='main_title',
        ),
        migrations.AddField(
            model_name='about',
            name='general',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='protfolio.general'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='name',
            field=models.CharField(default=1, max_length=300, verbose_name='Enter your name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Project End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.FileField(default=1, help_text='Only PNG, JPG, JPEG format supported', upload_to='project_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Project Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Project Start Date'),
        ),
        migrations.AlterField(
            model_name='general',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter Personal Email'),
        ),
        migrations.AlterField(
            model_name='general',
            name='policy',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Enter policy'),
        ),
        migrations.AlterField(
            model_name='general',
            name='terms',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Enter terms and conditions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Detail',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Project Details'),
        ),
    ]
